name = "flask-app"

[[services]]
  type = "python"
  script = "gunicorn -b 0.0.0.0:$PORT app:app"
  env = ["PYTHON_VERSION=3.8"]
  buildCommand = "pip install -r requirements.txt"

  [services.envs]
    BASIC_AUTH_USERNAME = { from = "env" }
    BASIC_AUTH_PASSWORD = { from = "env" }
    SECRET_KEY = { from = "env" }
    GOOGLE_SHEETS_CREDENTIALS = { from = "env" }
